version: '3.8' 

services:
  app:
    build: . # Path to the directory with your app's Dockerfile
    ports:
      - "8000:8000" # Expose FastAPI's port
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres_db:5432/datirovka

  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dativorka

volumes:
  postgres_data: